name: Puxar .env do DevOps Repo

on:
  push:
    branches:
    - main

jobs:
  copiar-env:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Reposit칩rio A (node-api)
      uses: actions/checkout@v3

    - name: Checkout do Reposit칩rio B (devops-repo)
      uses: actions/checkout@v3
      with:
        repository: rogerioanselmo/devops-repo
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: devops-repo

    - name: Debug - listar arquivos no devops-repo
      run: ls -la devops-repo/node-api

    - name: Copiar .env para raiz do reposit칩rio A
      run: cp devops-repo/node-api/.env .env

    - name: Exibir vari치vel de ambiente de exemplo
      run: |
        export $(cat .env | xargs)
        echo "EV_REPO: $ENV_REPO"
