name: Deploy Simple App to Local Minikube

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  fetch-env-from-repo-b:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Reposit칩rio A
      uses: actions/checkout@v3

    - name: Checkout Reposit칩rio B
      uses: actions/checkout@v3
      with:
        repository: rogerioanselmo/devops-repo
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: node-api

    - name: Copiar .env do reposit칩rio B
      run: cp .env .env

    - name: Verificar vari치vel de ambiente
      run: |
        export $(cat .env | xargs)
        echo "ENV_REPO: $ENV_REPO"
